services:
  server:
    build: ./server
    volumes:
      - ./server:/app
      - serverdata:/app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl.sh || exit 0" ]
      interval: 10s
      timeout: 10s
      retries: 10
 
  db:
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d database -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
  testrunner:
    build: ./testrunner
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - serverdata:./server
    

volumes:
  serverdata: